### ISSUE TITLE
What is causing this Startpage Image search behaviour?

### ISSUE THREAD

**Issue by LeLobster** [einaregilsson/Redirector#101]
I've created a redirect for Startpage's annoying image search proxying, but the images are broken when saved to disk unless I reload the page after it redirected the request from the proxy to the original image url.

```
{
    "createdBy": "Redirector v3.1.0",
    "createdAt": "2017-06-07T19:38:11.132Z",
    "redirects": [
        {
            "description": "Startpage Image Search",
            "exampleUrl": "https://ixquick-proxy.com/do/spg/show_picture=http://1.jpg&sp=2a3b",
            "exampleResult": "http://1.jpg",
            "error": null,
            "includePattern": ".*ixquick-proxy.*show_picture.*=(http[s]?(:|%3A).*[.]\\w{3})(&sp=\\w*)?",
            "excludePattern": "",
            "redirectUrl": "$1",
            "patternType": "R",
            "processMatches": "urlDecode",
            "disabled": false,
            "appliesTo": [
                "main_frame"
            ]
        }
    ]
}
```
Example url:
`https://ixquick-proxy.com/do/spg/show_picture.pl?l=english&rais=1&oiu=http%3A%2F%2Fwww.lessons4living.com%2Fimages%2Fpenclchk.gif&sp=2063c7f3426a38c0261cd82be8591509`

When trying to save the above image to disk it's appearing as `show_picture.pl.gif`, which is an unusable/broken image.  
After a reload of the redirected url the saved picture is fine.

Browser log from the first redirect:
```
"REDIRECTOR: Checking: main_frame: https://ixquick-proxy.com/do/spg/show_picture.pl?l=english&rais=1&oiu=http%3A%2F%2Fwww.lessons4living.com%2Fimages%2Fpenclchk.gif&sp=2063c7f3426a38c0261cd82be8591509"  background.js:6:3
"REDIRECTOR: Redirecting https://ixquick-proxy.com/do/spg/show_picture.pl?l=english&rais=1&oiu=http%3A%2F%2Fwww.lessons4living.com%2Fimages%2Fpenclchk.gif&sp=2063c7f3426a38c0261cd82be8591509 ===> http://www.lessons4living.com/images/penclchk.gif, type: main_frame, pattern: .*ixquick-proxy.*show_picture.*=(http[s]?(:|%3A).*[.]\w{3})(&sp=\w*)?"  background.js:6:3
GET 
https://ixquick-proxy.com/do/spg/show_picture.pl [HTTP/1.1 200 OK 129ms]
"REDIRECTOR: Checking: main_frame: http://www.lessons4living.com/images/penclchk.gif"  background.js:6:3
"REDIRECTOR: Ignoring http://www.lessons4living.com/images/penclchk.gif, was just redirected 347ms ago"  background.js:6:3
GET 
http://www.lessons4living.com/images/penclchk.gif [HTTP/1.1 200 OK 0ms]
GET 
http://www.lessons4living.com/images/penclchk.gif [HTTP/1.1 200 OK 0ms]
```

I'm not really knowledgeable in this kind of stuff but it looks like it still sends the original GET request after it should've redirected the url.

**Comment by einaregilsson** [comment]
If you look at this issue: https://github.com/einaregilsson/Redirector/issues/94 you'll see that from Firefox 52 there is a request sent to the original url as well. This is not the fault of Redirector, rather it is a Mozilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1345893 which is fixed in Firefox 55, which is still weeks away. There's nothing really that I can do about that :/

But this image proxy, are you always loading these images one at a time? I see that the redirect only applies to the main_frame, so it wouldn't redirect these images if they are being shown in another webpage for example.

**Comment by LeLobster** [comment]
Looking at the last comment on the bugzilla thread it's already fixed in 54, isn't it?

> are you always loading ...

Yes, the images are only shown via the ixquick proxy if you search through Startpage.com (a private wrapper for Google)   
You search for something, click the image and to view the full size you have to click 'view image', and then you're served the proxied link where possible.

Anyway if we're just waiting for Mozilla to release the fix which will affect this issue I guess this can be closed then.
Thank you for your work on this great addon!

**Comment by LeLobster** [comment]
Firefox 54.0 just landed in the stable branch but this bug is still present.  
There is no longer a GET request made to `https://ixquick-proxy.com/do/spg/show_picture.pl` after the redirect was processed but the image still saves as `show_picture.pl.jpg` and thus becomes unusable.  

```
"REDIRECTOR: Checking: main_frame: https://ixquick-proxy.com/do/spg/show_picture.pl?l=english&rais=1&oiu=https%3A%2F%2Famazingcarousel.com%2Fwp-content%2Fuploads%2Famazingcarousel%2F13%2Fimages%2Flightbox%2Fnight-in-the-city-lightbox.jpg&sp=81e4b7f28b9caf77d3a41e6c1d305c6b"  background.js:6:3
"REDIRECTOR: Redirecting https://ixquick-proxy.com/do/spg/show_picture.pl?l=english&rais=1&oiu=https%3A%2F%2Famazingcarousel.com%2Fwp-content%2Fuploads%2Famazingcarousel%2F13%2Fimages%2Flightbox%2Fnight-in-the-city-lightbox.jpg&sp=81e4b7f28b9caf77d3a41e6c1d305c6b ===> https://amazingcarousel.com/wp-content/uploads/amazingcarousel/13/images/lightbox/night-in-the-city-lightbox.jpg, type: main_frame, pattern: .*ixquick-proxy.*show_picture.*=(http[s]?(:|%3A).*([.]\w{3})?)&sp=\w*"  background.js:6:3
"REDIRECTOR: Checking: main_frame: https://amazingcarousel.com/wp-content/uploads/amazingcarousel/13/images/lightbox/night-in-the-city-lightbox.jpg"  background.js:6:3
"REDIRECTOR: Ignoring https://amazingcarousel.com/wp-content/uploads/amazingcarousel/13/images/lightbox/night-in-the-city-lightbox.jpg, was just redirected 222ms ago"  background.js:6:3
GET 
https://amazingcarousel.com/wp-content/uploads/amazingcarousel/13/images/lightbox/night-in-the-city-lightbox.jpg [HTTP/1.1 200 OK 1035ms]
```

```
"REDIRECTOR: Checking: main_frame: https://ixquick-proxy.com/do/spg/show_picture.pl?l=english&rais=1&oiu=https%3A%2F%2Fs-media-cache-ak0.pinimg.com%2Foriginals%2F5b%2F6f%2F38%2F5b6f38d097f6a93af17ea67f3dceca28.jpg&sp=f97930b2f6299d706383074912a72b7f"  background.js:6:3
"REDIRECTOR: Redirecting https://ixquick-proxy.com/do/spg/show_picture.pl?l=english&rais=1&oiu=https%3A%2F%2Fs-media-cache-ak0.pinimg.com%2Foriginals%2F5b%2F6f%2F38%2F5b6f38d097f6a93af17ea67f3dceca28.jpg&sp=f97930b2f6299d706383074912a72b7f ===> https://s-media-cache-ak0.pinimg.com/originals/5b/6f/38/5b6f38d097f6a93af17ea67f3dceca28.jpg, type: main_frame, pattern: .*ixquick-proxy.*show_picture.*=(http[s]?(:|%3A).*([.]\w{3})?)&sp=\w*"  background.js:6:3
"REDIRECTOR: Checking: main_frame: https://s-media-cache-ak0.pinimg.com/originals/5b/6f/38/5b6f38d097f6a93af17ea67f3dceca28.jpg"  background.js:6:3
"REDIRECTOR: Ignoring https://s-media-cache-ak0.pinimg.com/originals/5b/6f/38/5b6f38d097f6a93af17ea67f3dceca28.jpg, was just redirected 116ms ago"  background.js:6:3
GET 
https://s-media-cache-ak0.pinimg.com/originals/5b/6f/38/5b6f38d097f6a93af17ea67f3dceca28.jpg [HTTP/1.1 200 OK 906ms]
```

**Comment by einaregilsson** [comment]
Hmm, if I click on the View image link I get the real url, and when I then save I just get the filename. Are you right clicking on the link and clicking Save As there? Because that won't work.

**Comment by LeLobster** [comment]
I open the image link in a new tab by middle clicking `View Image (always anonymously)` then I right click the image and choose `Save Image As...`

It's not caused by another extension because it also happens on a clean profile in `54.0b14 dev`

Are you on Linux? Because maybe it's a windows only thing.

**Comment by einaregilsson** [comment]
Ok, weird. I could reproduce this the first time I tried it, but later when I tried the same thing I always got the actual filename. In any case, this doesn't seem like something I can influence from the extension. I use a very simple API that Firefox provides, that basically just tells me "This url is being requested" and I can return a different URL if I want to redirect. I have no access to the internals that decide which image name to use in the save image as dialog.

**Comment by LeLobster** [comment]
> I could reproduce this the first time

This is something I found out as well, if you load the same url a second time everything is fine.  
I think the fact that the current WE API's are so young and underdeveloped there are still way too many bugs. Because the image name isn't what's causing the file to become corrupt, that can't be the reason.  
There is something internal which is screwing up.  

I've been experimenting with the webRequest and webNavigation API's a bit but found them really unreliable in some cases.  

Anyway, I guess this issue can be closed? I suppose it would serve better on bugzilla then here.

**Comment by einaregilsson** [comment]
@LeLobster Yeah, a bug for Mozilla would be good. Closing this, hopefully they'll fix this in a future version of FF.
